### PR TITLE
Add detailed documentation to existing packages

### PR DESCRIPTION
**Pull request by alanssitis**
## Brief Description
Update documentation throughout the repo.

## Details
Add documentation to every package.

## Tasks

- [x] Updated Documentation

### CODE REVIEW

**Comment by alanssitis** [comment]
@Reschivon Do we need launch file descriptions in package READMEs?

**Comment by Reschivon** [comment]
I think a brief one line summary of what each file does would be nice. I think the rest of the readme would give the necessary context for what it does specifically. In some public ROS packages we often get a pile of launch files and it's ambiguous what they do.

**Comment by alanssitis** [comment]
> I think a brief one line summary of what each file does would be nice. I think the rest of the readme would give the necessary context for what it does specifically. In some public ROS packages we often get a pile of launch files and it's ambiguous what they do.

Makes sense. Done!

**Review by Reschivon — APPROVED** [review]
Looks good, each package is described concisely and the addition of a file tree was a nice touch. Thanks Alan.

**Pull request merged**
